apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app-rollout
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: hello-app-rollout
  template:
    metadata:
      labels:
        app: hello-app-rollout
    spec:
      containers:
        - name: hello-app
          image: docker-k8s-lab:v1
          ports:
            - containerPort: 5000
